# Generated by Django 5.1.5 on 2025-01-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='company_name',
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
