# Generated by Django 5.1.5 on 2025-01-18 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_remove_jobapplication_company_name_job_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(default='default_resume.pdf', upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobseeker.resume'),
        ),
    ]
